name: pull-requests

# disable CI builds
trigger: none

# Only trigger for PR's targeting 4.0
pr:
  branches:
    include:
      - 4.0
  autoCancel: "true"

strategy:
  matrix:
    linux-3.5:
      javaVersion: 8
      serverVersion: "-e 3.5"
      imageName: "ubuntu-16.04"
    linux-4.0:
      javaVersion: 11
      serverVersion: "-e 4.0"
      imageName: "ubuntu-16.04"
    windows-3.5:
      javaVersion: 8
      serverVersion: "-e 3.5"
      imageName: "vs2017-win2016"
    windows-4.0:
      javaVersion: 11
      serverVersion: "-e 4.0"
      imageName: "vs2017-win2016"

pool:
  vmImage: $(imageName)

variables:
  group: teamcity

steps:
  - template: "steps.yml"
    parameters:
      name: $(Agent.JobName)
      javaVersion: $(javaVersion)
      serverVersion: $(serverVersion)
